# Generated by Django 4.2 on 2023-04-16 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='학년', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartofSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='품사', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='학교', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='학교기출', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='학생', max_length=10)),
                ('grade', models.ForeignKey(help_text='학년', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.grade')),
                ('school', models.ForeignKey(help_text='학교', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.school')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목(예:고3 2023년 3월)', max_length=200)),
                ('question', models.CharField(help_text='질문', max_length=200, null=True)),
                ('year', models.CharField(help_text='연도', max_length=10)),
                ('answers', models.IntegerField(help_text='정답', null=True)),
                ('context', models.TextField(help_text='지문', max_length=3000, null=True)),
                ('exam', models.ManyToManyField(help_text='기출입력', null=True, to='catalog.schoolexam')),
                ('grade', models.ForeignKey(help_text='학년', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.grade')),
            ],
        ),
    ]
