# Generated by Django 4.2 on 2023-04-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='exam',
        ),
    ]
