# Generated by Django 4.2 on 2023-04-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_article_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='no',
            field=models.IntegerField(help_text='문항번호', null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(help_text='학년', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='partofspeech',
            name='name',
            field=models.CharField(help_text='품사', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(help_text='학교', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='schoolexam',
            name='name',
            field=models.CharField(help_text='학교기출', max_length=200, null=True, unique=True),
        ),
    ]
