# Generated by Django 4.2 on 2023-04-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_article_no_alter_grade_name_alter_partofspeech_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='answers',
            new_name='answer',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='제목(예:고3 2023년 3월 18번)', max_length=200),
        ),
    ]
