# Generated by Django 4.2 on 2023-04-17 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_answers_article_answer_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='answer',
            field=models.IntegerField(help_text='정답', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='no',
            field=models.IntegerField(help_text='문항번호', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.CharField(help_text='연도', max_length=4),
        ),
    ]
