# Generated by Django 4.2 on 2023-04-17 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_article_answer_alter_article_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admissiondate',
            field=models.DateField(help_text='등록일', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='answer',
            field=models.IntegerField(help_text='정답[1-5]', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
