# Generated by Django 4.2 on 2023-04-17 16:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_student_admissiondate_alter_article_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolexam',
            name='name',
        ),
        migrations.AddField(
            model_name='schoolexam',
            name='answer',
            field=models.IntegerField(help_text='정답[1-5]', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='schoolexam',
            name='context',
            field=models.TextField(help_text='지문', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='schoolexam',
            name='grade',
            field=models.ForeignKey(help_text='학년', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.grade'),
        ),
        migrations.AddField(
            model_name='schoolexam',
            name='no',
            field=models.IntegerField(help_text='문항번호', null=True),
        ),
        migrations.AddField(
            model_name='schoolexam',
            name='quarter',
            field=models.CharField(help_text='1학기 중간', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schoolexam',
            name='question',
            field=models.CharField(help_text='질문', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schoolexam',
            name='school',
            field=models.ForeignKey(help_text='학교', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.school'),
        ),
        migrations.AddField(
            model_name='schoolexam',
            name='writing',
            field=models.CharField(help_text='서술형정답', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='schoolexam',
            name='year',
            field=models.CharField(help_text='연도', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='no',
            field=models.IntegerField(help_text='문항번호', null=True),
        ),
    ]
