# Generated by Django 4.2 on 2023-04-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_schoolexam_name_schoolexam_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolexam',
            name='quarter',
            field=models.CharField(help_text='1학기 중간', max_length=10, null=True),
        ),
    ]
