# Generated by Django 4.2 on 2023-06-04 12:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_schoolexam_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolexam',
            name='article',
            field=models.ForeignKey(help_text='원본', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.article'),
        ),
        migrations.CreateModel(
            name='ArticleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testdate', models.DateField(blank=True, null=True)),
                ('answer', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.article')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.student')),
            ],
            options={
                'ordering': ['student'],
            },
        ),
    ]
