# Generated by Django 4.2 on 2023-06-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_articletest_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletest',
            old_name='answer',
            new_name='reply',
        ),
        migrations.AddField(
            model_name='articletest',
            name='correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
